### ISSUE TITLE
Example application

### ISSUE THREAD

**Issue by hagenburger** [efacilitation/gulp-livingstyleguide#1]
Do you maybe want to create an example application within https://github.com/hagenburger/livingstyleguide-example? I guess this could be very useful.

I just linked to this repository in [the README](https://github.com/hagenburger/livingstyleguide/tree/development#gulp) and will merge to master later.

**Comment by alexlawrence** [comment]
Since this issue was very old we figured that we don´t find the time for this. Pull requests are very welcome :)
